alter table UNTITLED_CURRENCY_RATE add constraint FK_UNTITLED_CURRENCY_RATE_ON_CURRENCY foreign key (CURRENCY_ID) references UNTITLED_CURRENCY(ID);
create index IDX_UNTITLED_CURRENCY_RATE_ON_CURRENCY on UNTITLED_CURRENCY_RATE (CURRENCY_ID);
