alter table UNTITLED_FORECAST_BN alter column FORECAST_SUMM5 rename to FORECAST_SUMM5__U54786 ^
alter table UNTITLED_FORECAST_BN alter column FORECAST_SUMM4 rename to FORECAST_SUMM4__U38114 ^
alter table UNTITLED_FORECAST_BN alter column FORECAST_SUMM3 rename to FORECAST_SUMM3__U21003 ^
alter table UNTITLED_FORECAST_BN alter column FORECAST_SUMM2 rename to FORECAST_SUMM2__U13949 ^
alter table UNTITLED_FORECAST_BN alter column FORECAST_SUMM1 rename to FORECAST_SUMM1__U38508 ^
alter table UNTITLED_FORECAST_BN alter column OUT_SUMM5 rename to OUT_SUMM5__U14514 ^
alter table UNTITLED_FORECAST_BN alter column OUT_SUMM4 rename to OUT_SUMM4__U18857 ^
alter table UNTITLED_FORECAST_BN alter column OUT_SUMM3 rename to OUT_SUMM3__U55393 ^
alter table UNTITLED_FORECAST_BN alter column OUT_SUMM2 rename to OUT_SUMM2__U15468 ^
alter table UNTITLED_FORECAST_BN alter column OUT_SUMM1 rename to OUT_SUMM1__U87884 ^
alter table UNTITLED_FORECAST_BN alter column IN_SUMM5 rename to IN_SUMM5__U62442 ^
alter table UNTITLED_FORECAST_BN alter column IN_SUMM4 rename to IN_SUMM4__U70225 ^
alter table UNTITLED_FORECAST_BN alter column IN_SUMM3 rename to IN_SUMM3__U33280 ^
alter table UNTITLED_FORECAST_BN alter column IN_SUMM2 rename to IN_SUMM2__U97023 ^
alter table UNTITLED_FORECAST_BN alter column IN_SUMM1 rename to IN_SUMM1__U81372 ^
alter table UNTITLED_FORECAST_BN alter column BALANCE rename to BALANCE__U36138 ^
