create table UNTITLED_FORECAST_BN (
    ID varchar(36) not null,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    BUSINESS_DIRECTION_ID varchar(36),
    BALANCE_DATE date,
    BALANCE double precision,
    IN_SUMM1 double precision,
    IN_SUMM2 double precision,
    IN_SUMM3 double precision,
    IN_SUMM4 double precision,
    IN_SUMM5 double precision,
    OUT_SUMM1 double precision,
    OUT_SUMM2 double precision,
    OUT_SUMM3 double precision,
    OUT_SUMM4 double precision,
    OUT_SUMM5 double precision,
    FORECAST_SUMM1 double precision,
    FORECAST_SUMM2 double precision,
    FORECAST_SUMM3 double precision,
    FORECAST_SUMM4 double precision,
    FORECAST_SUMM5 double precision,
    --
    primary key (ID)
);